### ISSUE TITLE
AttributeError: module 'snudown' has no attribute 'markdown'

### ISSUE THREAD

**Issue by ohhdemgirls** [libertysoft3/reddit-html-archiver#16]
```
python3 write_html.py

Traceback (most recent call last):
  File "write_html.py", line 754, in <module>
    generate_html(args.min_score, args.min_comments, hide_deleted_comments)
  File "write_html.py", line 125, in generate_html
    write_link_page(subs, l, sub, hide_deleted_comments)
  File "write_html.py", line 269, in write_link_page
    '###BODY###':               snudown.markdown(c['body'].replace('&gt;','>')),
AttributeError: module 'snudown' has no attribute 'markdown'

```

EDIT: You can close this, I'm an idiot and fixed with by install snudown via python3 (y)

**Comment by ifteqarahmed** [comment]
Hi im trying this command python3 setup.py install and it shows a lot of errors 
can u tell me the procedure of how to install snudown properly
