### ISSUE TITLE
Issue getting write_html past generate_html

### ISSUE THREAD

**Issue by 5000thinmints** [libertysoft3/reddit-html-archiver#23]
Here's the error under win10 having just installed latest python and snudown, my data folder is about a gig and a half. I assumed min score/comments and deleted are all set to something by default.

E:\Myfolder\reddittohtml>write_html.py
Traceback (most recent call last):
  File "E:\Myfolder\reddittohtml\write_html.py", line 774, in <module>
    generate_html(args.min_score, args.min_comments, hide_deleted_comments)
  File "E:\Myfolder\reddittohtml\write_html.py", line 114, in generate_html
    raw_links = load_links(d, sub, True)
  File "E:\Myfolder\reddittohtml\write_html.py", line 625, in load_links
    comments_file_path = daily_path + '/' + link_row['id'] + '.csv'
KeyError: 'id'

Here's when I do try it with min and max etc set;

E:\Myfolder\reddittohtml>write_html.py --min-score -4 --min-comments 2 --hide-deleted-comments
Traceback (most recent call last):
  File "E:\Myfolder\reddittohtml\write_html.py", line 774, in <module>
    generate_html(args.min_score, args.min_comments, hide_deleted_comments)
  File "E:\Myfolder\reddittohtml\write_html.py", line 114, in generate_html
    raw_links = load_links(d, sub, True)
  File "E:\Myfolder\reddittohtml\write_html.py", line 625, in load_links
    comments_file_path = daily_path + '/' + link_row['id'] + '.csv'
KeyError: 'id'

**Comment by libertysoft3** [comment]
I pushed a fix, will you try again?

**Comment by 5000thinmints** [comment]
So it look longer to print out an error this time, if it helps some of the reddit subs I'm pulling from use non-english characters (ex hindi, korean) frequently

E:\Myfolder\reddittohtml>write_html.py
Traceback (most recent call last):
  File "E:\Myfolder\reddittohtml\write_html.py", line 774, in <module>
    generate_html(args.min_score, args.min_comments, hide_deleted_comments)
  File "E:\Myfolder\reddittohtml\write_html.py", line 119, in generate_html
    write_link_page(subs, l, sub, hide_deleted_comments)
  File "E:\Myfolder\reddittohtml\write_html.py", line 288, in write_link_page
    '###BODY###':               snudown.markdown(c['body'].replace('&gt;','>')),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 382: invalid continuation byte

**Comment by libertysoft3** [comment]
Cool, forward progress. I'm not too hip with Windows, but can you try running the 2 commands listed here under "Windows users may need to run"? https://github.com/libertysoft3/reddit-html-archiver/blob/master/README.md#install

**Comment by 5000thinmints** [comment]
Running the commands with cmd under admin still has the issue;

E:\Myfolder\reddittohtml>chcp 65001
Active code page: 65001

E:\Myfolder\reddittohtml>set PYTHONIOENCODING=utf-8

E:\Myfolder\reddittohtml>write_html.py
Traceback (most recent call last):
  File "E:\Myfolder\reddittohtml\write_html.py", line 774, in <module>
    generate_html(args.min_score, args.min_comments, hide_deleted_comments)
  File "E:\Myfolder\reddittohtml\write_html.py", line 119, in generate_html
    write_link_page(subs, l, sub, hide_deleted_comments)
  File "E:\Myfolder\reddittohtml\write_html.py", line 288, in write_link_page
    '###BODY###':               snudown.markdown(c['body'].replace('&gt;','>')),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 382: invalid continuation byte
