### ISSUE TITLE
Error on fetch_links.py every time

### ISSUE THREAD

**Issue by FaolanX** [libertysoft3/reddit-html-archiver#33]
Traceback (most recent call last):
  File "fetch_links.py", line 219, in <module>
    fetch_links(args.subreddit, args.date_start, args.date_stop, args.limit, args.score, self_only)
  File "fetch_links.py", line 71, in fetch_links
    comments_results = list(api.search_comments(**comment_params))
  File "C:\Python38\lib\site-packages\psaw\PushshiftAPI.py", line 238, in _search
    for response in self._handle_paging(url):
  File "C:\Python38\lib\site-packages\psaw\PushshiftAPI.py", line 218, in _handle_paging
    received_size = int(data['metadata']['size'])
KeyError: 'metadata'

Python 3.8.5 on Windows amd64

**Comment by Tobbinloggin** [comment]
I get the same error.

**Comment by libertysoft3** [comment]
Pushshift has been all messed up lately. You can try skipping over that post/date.

**Comment by biebersoft** [comment]
This doesnt help
