### ISSUE TITLE
Error while running fetch

### ISSUE THREAD

**Issue by logicpipeline** [libertysoft3/reddit-html-archiver#34]
fetching submissions 2021-01-01 to 2021-02-01...
/home/runner/.local/lib/python3.8/site-packages/psaw/PushshiftAPI.py:192: UserWarning: Got non 200 code 429
  warnings.warn("Got non 200 code %s" % response.status_code)
/home/runner/.local/lib/python3.8/site-packages/psaw/PushshiftAPI.py:180: UserWarning: Unable to connect to pushshift.io. Retrying after backoff.
  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")
processing 3330 links
Traceback (most recent call last):
  File "./fetch_links.py", line 219, in <module>
    fetch_links(args.subreddit, args.date_start, args.date_stop, args.limit, args.score, self_only)
  File "./fetch_links.py", line 71, in fetch_links
    comments_results = list(api.search_comments(**comment_params))
  File "/home/runner/.local/lib/python3.8/site-packages/psaw/PushshiftAPI.py", line 238, in _search
    for response in self._handle_paging(url):
  File "/home/runner/.local/lib/python3.8/site-packages/psaw/PushshiftAPI.py", line 218, in _handle_paging
    received_size = int(data['metadata']['size'])
KeyError: 'metadata'

**Comment by libertysoft3** [comment]
you got flagged as abusive
