### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by moom0o** [libertysoft3/reddit-html-archiver#35]
```
Traceback (most recent call last):
  File "./fetch_links.py", line 219, in <module>
    fetch_links(args.subreddit, args.date_start, args.date_stop, args.limit, args.score, self_only)
  File "./fetch_links.py", line 71, in fetch_links
    comments_results = list(api.search_comments(**comment_params))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psaw\PushshiftAPI.py", line 238, in _search
    for response in self._handle_paging(url):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psaw\PushshiftAPI.py", line 218, in _handle_paging
    received_size = int(data['metadata']['size'])
KeyError: 'metadata'
```

**Comment by libertysoft3** [comment]
You are seeing an API / PushshiftAPI issue
